#!/bin/bash

VPCID=$(aws ec2 create-vpc --cidr-block "10.0.0.0/16" | grep '"VpcId":' | cut -d'"' -f4)
SUBNET_PUBLIC=$(aws ec2 create-subnet --cidr-block "10.0.0.0/24" --vpc-id ${VPCID} | grep '"SubnetId":' | cut -d'"' -f4)
aws ec2 modify-subnet-attribute --map-public-ip-on-launch --subnet-id ${SUBNET_PUBLIC}
IGW=$(aws ec2 create-internet-gateway | grep '"InternetGatewayId":' | cut -d'"' -f4)
aws ec2 attach-internet-gateway --internet-gateway-id ${IGW} --vpc-id ${VPCID}
ROUTETABLEPUBLIC=$(aws ec2 create-route-table --vpc-id ${VPCID} | grep '"RouteTableId":' | cut -d'"' -f4)
# rtb-0b8f3072752c12270 => Route Table Publique
aws ec2 associate-route-table --route-table-id ${ROUTETABLEPUBLIC} --subnet-id ${SUBNET_PUBLIC}
IPALLOC=$(aws ec2 allocate-address | grep '"AllocationId":' | cut -d'"' -f4)
SGPUBLIC=$(aws ec2 create-security-group --vpc-id ${VPCID} --description "SG-PUBLIC" --group-name "SG-PUBLIC" | grep '"GroupId":' | cut -d'"' -f4)
aws ec2 authorize-security-group-ingress --group-id ${SGPUBLIC} --protocol "tcp" --port "22" --cidr "0.0.0.0/0"
INSTANCEID=$(aws ec2 run-instances --image-id ami-0f15e0a4c8d3ee5fe --count 1 --instance-type t2.micro --key-name taty_key  --security-group-ids ${SGBPUBLIC} --subnet-id ${SUBNET_PUBLIC} | grep '"InstanceId":' | cut -d'"' -f4)
INSTANCEIP=$(aws ec2 describe-instances --instance-ids ${INSTANCEID} | grep '"PublicIp":'| cut -d'"' -f4| uniq)

echo "VPCID : ${VPCID}" > /var/lib/jenkins/workspace/Common/deployed/${PROJECT_NAME}.txt
echo "SUBNET_PUBLIC : ${SUBNET_PUBLIC}"
echo "IGW : ${IGW}"
echo "ROUTE TABLE : ${ROUTETABLEPUBLIC}"
echo "IP ALLOC : ${IPALLOC}"
echo "NGW : ${NGW}"
echo "SECURITY GROUP PUBLIC : ${SGPUBLIC}"
echo "INSTANCE ID : ${INSTANCEID}"
echo "INSTANCE IP : ${INSTANCEIP}"
