#!/bin/bash
VPCID=$(aws ec2 create-vpc --cidr-block "10.0.0.0/16" | grep '"VpcId":' | cut -d'"' -f4)
SUBNET_PUBLIC=$(aws ec2 create-subnet --cidr-block "10.0.0.0/24" --vpc-id ${VPCID} | grep '"SubnetId":' | cut -d'"' -f4)
aws ec2 modify-subnet-attribute --map-public-ip-on-launch --subnet-id ${SUBNET_PUBLIC}
SUBNET_PRIVATE=$(aws ec2 create-subnet --cidr-block "10.0.1.0/24" --vpc-id ${VPCID} | grep '"SubnetId":' | cut -d'"' -f4)
IGW=$(aws ec2 create-internet-gateway | grep '"InternetGatewayId":' | cut -d'"' -f4)
aws ec2 attach-internet-gateway --internet-gateway-id ${IGW} --vpc-id ${VPCID}
ROUTETABLEPUBLIC=$(aws ec2 create-route-table --vpc-id ${VPCID} | grep '"RouteTableId":' | cut -d'"' -f4)
# rtb-0b8f3072752c12270 => Route Table Publique
aws ec2 create-route --route-table-id ${ROUTETABLEPUBLIC} --destination-cidr-block "0.0.0.0/0" --gateway-id ${IGW}
aws ec2 associate-route-table --route-table-id ${ROUTETABLEPUBLIC} --subnet-id ${SUBNET_PUBLIC}
IPALLOC=$(aws ec2 allocate-address | grep '"AllocationId":' | cut -d'"' -f4)
NGW=$(aws ec2 create-nat-gateway --allocation-id ${IPALLOC} --subnet-id ${SUBNET_PUBLIC} | grep '"NatGatewayId":' | cut -d'"' -f4)
sleep 10
ROUTETABLEPRIVEE=$(aws ec2 create-route-table --vpc-id ${VPCID} | grep '"RouteTableId":' | cut -d'"' -f4)
aws ec2 create-route --route-table-id ${ROUTETABLEPRIVEE} --destination-cidr-block "0.0.0.0/0" --nat-gateway-id ${NGW}
aws ec2 associate-route-table --route-table-id ${ROUTETABLEPRIVEE} --subnet-id ${SUBNET_PRIVATE}
SGPUBLIC=$(aws ec2 create-security-group --vpc-id ${VPCID} --description "SG-PUBLIC" --group-name "SG-PUBLIC" | grep '"GroupId":' | cut -d'"' -f4)
SGPRIVATE=$(aws ec2 create-security-group --vpc-id ${VPCID} --description "SG-PRIVATE" --group-name "SG-PRIVATE" | grep '"GroupId":' | cut -d'"' -f4)
aws ec2 authorize-security-group-ingress --group-id ${SGPUBLIC} --protocol "tcp" --port "22" --cidr "0.0.0.0/0"
aws ec2 authorize-security-group-ingress --group-id ${SGPRIVATE} --protocol "tcp" --port "22" --source-group ${SGPUBLIC}
aws ec2 authorize-security-group-ingress --group-id ${SGPRIVATE} --protocol "tcp" --port "22" --source-group ${SGPUBLIC}

aws ec2 run-instances --subnet-id ${SUBNET_PUBLIC} --image-id ami-0f15e0a4c8d3ee5fe --instance-type t2.micro --key-name "test_keypair" --security-group-ids ${SGPUBLIC}
#i-07c820eef1530170b => Instance publique

aws ec2 run-instances --subnet-id ${SUBNET_PRIVATE} --image-id ami-0f15e0a4c8d3ee5fe --instance-type t2.micro --key-name "test_keypair" --security-group-ids ${SGPRIVATE}
#i-0cab9423178d0f834 => Instance privée

echo "VPCID : ${VPCID}"
echo "SUBNET_PUBLIC : ${SUBNET_PUBLIC}"
echo "SUBNET_PRIVATE : ${SUBNET_PRIVATE}"
echo "IGW : ${IGW}"
echo "ROUTE TABLE : ${ROUTETABLEPUBLIC}"
echo "IP ALLOC : ${IPALLOC}"
echo "NGW : ${NGW}"
echo "ROUTE TABLE PRIVEE : ${ROUTETABLEPRIVEE}"
echo "SECURITY GROUP PUBLIC : ${SGPUBLIC}"
echo "SECURITY GROUP PRIVATE: ${SGPRIVATE}"

exit
3
